//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Declaration()
        {
            this.ClassAssertions = new HashSet<ClassAssertion>();
            this.ClassAssertions1 = new HashSet<ClassAssertion>();
            this.DataPropertyAssertions = new HashSet<DataPropertyAssertion>();
            this.DataPropertyAssertions1 = new HashSet<DataPropertyAssertion>();
            this.DataPropertyDomains = new HashSet<DataPropertyDomain>();
            this.DataPropertyDomains1 = new HashSet<DataPropertyDomain>();
            this.DataPropertyRanges = new HashSet<DataPropertyRange>();
            this.Keywords = new HashSet<Keyword>();
            this.ObjectPropertyAssertions = new HashSet<ObjectPropertyAssertion>();
            this.ObjectPropertyAssertions1 = new HashSet<ObjectPropertyAssertion>();
            this.ObjectPropertyAssertions2 = new HashSet<ObjectPropertyAssertion>();
            this.ObjectPropertyDomains = new HashSet<ObjectPropertyDomain>();
            this.ObjectPropertyDomains1 = new HashSet<ObjectPropertyDomain>();
            this.ObjectPropertyRanges = new HashSet<ObjectPropertyRange>();
            this.ObjectPropertyRanges1 = new HashSet<ObjectPropertyRange>();
        }
    
        public long Id { get; set; }
        public string Type { get; set; }
        public string Iri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAssertion> ClassAssertions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAssertion> ClassAssertions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPropertyAssertion> DataPropertyAssertions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPropertyAssertion> DataPropertyAssertions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPropertyDomain> DataPropertyDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPropertyDomain> DataPropertyDomains1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPropertyRange> DataPropertyRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keyword> Keywords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyAssertion> ObjectPropertyAssertions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyAssertion> ObjectPropertyAssertions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyAssertion> ObjectPropertyAssertions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyDomain> ObjectPropertyDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyDomain> ObjectPropertyDomains1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyRange> ObjectPropertyRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPropertyRange> ObjectPropertyRanges1 { get; set; }
    }
}
