//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiceContext : DbContext
    {
        public RiceContext()
            : base("name=RiceContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnotationAssertion> AnnotationAssertions { get; set; }
        public virtual DbSet<ClassAssertion> ClassAssertions { get; set; }
        public virtual DbSet<DataPropertyAssertion> DataPropertyAssertions { get; set; }
        public virtual DbSet<DataPropertyDomain> DataPropertyDomains { get; set; }
        public virtual DbSet<DataPropertyRange> DataPropertyRanges { get; set; }
        public virtual DbSet<Declaration> Declarations { get; set; }
        public virtual DbSet<ObjectPropertyAssertion> ObjectPropertyAssertions { get; set; }
        public virtual DbSet<ObjectPropertyDomain> ObjectPropertyDomains { get; set; }
        public virtual DbSet<ObjectPropertyRange> ObjectPropertyRanges { get; set; }
    }
}
